---
name: "Contributors by Organisation Action"
author: "hcookie"
description: "A GitHub Action to report out contributors and contributions to a repository or organization sorted by organisations"
runs:
  using: "docker"
  image: "docker://ghcr.io/hcookie/organizational_contributors:latest"
branding:
  icon: "users"
  color: "green"
